### Feature Teacher — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllTeachers
GET {{baseUrl}}/api/docentes

###

# @name getOneTeacher
GET {{baseUrl}}/api/docentes/{{id}}
