### UPDATE SUBMISSION - PUT
PUT http://localhost:4000/api/entregas/1
Content-Type: application/json

{
  "referencia_id": 1,
  "lesson_id": 1,
  "enrollment_id": 1,
  "fecha_inicio": "2026-09-29T08:00:00",
  "fecha_fin": "2026-09-29T10:30:00",
  "total": 98,
  "estado": "completada",
  "observaciones": "Entrega actualizada"
}

### UPDATE SUBMISSION - PATCH
PATCH http://localhost:4000/api/entregas/1
Content-Type: application/json

{
  "total": 100,
  "observaciones": "Entrega revisada"
}
