### UPDATE CERTIFICATE - PUT
PUT http://localhost:4000/api/certificates/1
Content-Type: application/json

{
  "enrollment_id": 1,
  "name": "Certificado actualizado",
  "description": "Descripción actualizada",
  "isActive": true
}

### UPDATE CERTIFICATE - PATCH
PATCH http://localhost:4000/api/certificates/1
Content-Type: application/json

{
  "name": "Certificado actualizado parcialmente"
}
