### UPDATE MODULE - PUT
PUT http://localhost:4000/api/modulos/1
Content-Type: application/json

{
  "course_id": 1,
  "name": "Módulo actualizado",
  "description": "Descripción actualizada del módulo",
  "isActive": true
}

### UPDATE MODULE - PATCH
PATCH http://localhost:4000/api/modulos/1
Content-Type: application/json

{
  "name": "Módulo parcial actualizado"
}
