### Feature Course — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllCourses
GET {{baseUrl}}/api/cursos

###

# @name getOneCourse
GET {{baseUrl}}/api/cursos/{{id}}
