### UPDATE PROGRESS - PUT
PUT http://localhost:4000/api/progress/1
Content-Type: application/json

{
  "enrollment_id": 1,
  "name": "Progreso actualizado",
  "description": "Seguimiento actualizado",
  "isActive": true
}

### UPDATE PROGRESS - PATCH
PATCH http://localhost:4000/api/progress/1
Content-Type: application/json

{
  "name": "Progreso parcial actualizado"
}
